import json

data = {
    "metadata": {
        "title": "Saudi Telecom Prepaid Packages Database (دليل باقات مسبق الدفع في السعودية)",
        "source": "Official Operator Websites & Communications, Space & Technology Commission (CST / هيئة الاتصالات والفضاء والتقنية)",
        "currency": "SAR (ريال سعودي)",
        "vat_rate": 0.15,
        "last_updated": "2026-09-18",
        "regulatory_notes": {
            "voice_metering": "All local voice calls in Saudi Arabia are metered per second by CST regulations (حساب المكالمات بالثانية).",
            "data_metering": "Standard mobile data session metering block across all operators is 100 KB (حساب البيانات في كتل بحجم 100 كيلوبايت لكل جلسة).",
            "hotspot_restriction": "Unlimited social media/apps allowances generally do NOT apply to hotspot/tethering; hotspot data is deducted from the general data balance (بث الإنترنت الهوتسبوت يُخصم من البيانات العامة).",
            "vpn_voip_rule": "In-app VoIP calls (WhatsApp, etc.) are restricted by regulation; using VPN routes all traffic to general data (استخدام VPN يخصم من البيانات العامة وليس السوشيال)."
        }
    },
    "providers": [
        {
            "id": "stc",
            "name_ar": "إس تي سي (stc)",
            "name_en": "stc",
            "network": "stc (المشغل الرئيسي)",
            "type": "MNO (مشغل رئيسي)",
            "website": "https://www.stc.com.sa/",
            "hidden_conditions": {
                "metering_block_data": "100 KB (كل جلسة تقرب لأقرب 100 كيلوبايت)",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": True,
                "vowifi_notes": "مدعومة رسميًا على سوا (stc WiFi Calling) بدون رسوم إضافية وتخصم من دقائق الباقة.",
                "volte_supported": True,
                "throttling_fup": "لا يوجد خنق سرعة على سعة البيانات العامة المحددة. في باقات السوشيال المفتوح تطبق سياسة الاستخدام العادل لمنع الاستخدام التجاري فقط.",
                "hotspot_policy": "الهوتسبوت يخصم من رصيد البيانات العامة.",
                "data_rollover": False
            },
            "packages": [
                {
                    "name_ar": "سوا بيسك",
                    "name_en": "Sawa Basic",
                    "price_base": 30.00,
                    "price_vat": 34.50,
                    "validity_days": 28,
                    "general_data_gb": 1.0,
                    "social_data_gb": 1.0,
                    "unlimited_social": False,
                    "local_minutes": 100,
                    "special_perks_ar": "أرخص باقة أساسية للمكالمات الخفيفة",
                    "special_perks_en": "Lowest entry-level plan for basic usage"
                },
                {
                    "name_ar": "سوا لايك بلس (العرض الجديد)",
                    "name_en": "Sawa Like Plus (Promo)",
                    "price_base": 75.00,
                    "price_vat": 86.25,
                    "validity_days": 28,
                    "general_data_gb": 20.0,
                    "social_data_gb": 20.0,
                    "unlimited_social": False,
                    "local_minutes": 540,
                    "special_perks_ar": "مضاعفة البيانات (20 جيجا عام + 20 جيجا سوشيال) وتغطية stc الأوسع",
                    "special_perks_en": "Doubled data allowance (20GB general + 20GB social), widest stc coverage"
                },
                {
                    "name_ar": "سوا كابتن",
                    "name_en": "Sawa Captain",
                    "price_base": 85.00,
                    "price_vat": 97.75,
                    "validity_days": 28,
                    "general_data_gb": 30.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": False,
                    "local_minutes": 600,
                    "special_perks_ar": "30 جيجا نت عام + خرائط قوقل وواتساب لا محدود مخصصة لكباتن التوصيل والتنقل",
                    "special_perks_en": "30GB general data + unlimited Google Maps & WhatsApp, ideal for couriers"
                },
                {
                    "name_ar": "سوا شير بلس",
                    "name_en": "Sawa Share Plus",
                    "price_base": 115.00,
                    "price_vat": 132.25,
                    "validity_days": 28,
                    "general_data_gb": 40.0,
                    "social_data_gb": 55.0,
                    "unlimited_social": False,
                    "local_minutes": 1520,
                    "special_perks_ar": "إجمالي 95 جيجابايت مع دقائق وفيرة",
                    "special_perks_en": "Total 95GB combined data with high call volume"
                },
                {
                    "name_ar": "سوا 120",
                    "name_en": "Sawa 120",
                    "price_base": 120.00,
                    "price_vat": 138.00,
                    "validity_days": 28,
                    "general_data_gb": 45.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "social_apps": ["WhatsApp", "Snapchat", "Facebook"],
                    "local_minutes": 1210,
                    "special_perks_ar": "45 جيجا نت عام + واتساب وسناب وفيسبوك مفتوح",
                    "special_perks_en": "45GB general data + unlimited WhatsApp, Snapchat & Facebook"
                },
                {
                    "name_ar": "سوا 150",
                    "name_en": "Sawa 150",
                    "price_base": 150.00,
                    "price_vat": 172.50,
                    "validity_days": 28,
                    "general_data_gb": 70.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1150,
                    "special_perks_ar": "70 جيجا نت عام + سوشيال ميديا لا محدود بالكامل",
                    "special_perks_en": "70GB general data + fully unlimited social media"
                },
                {
                    "name_ar": "سوا بوست بلس",
                    "name_en": "Sawa Post Plus",
                    "price_base": 170.00,
                    "price_vat": 195.50,
                    "validity_days": 28,
                    "general_data_gb": 74.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 500,
                    "special_perks_ar": "مكالمات لا محدودة داخل stc + 500 دقيقة خارج الشبكة + سوشيال لا محدود",
                    "special_perks_en": "Unlimited on-net stc calls + 500 off-net mins + unlimited social"
                },
                {
                    "name_ar": "سوا ستار بلس",
                    "name_en": "Sawa Star Plus",
                    "price_base": 240.00,
                    "price_vat": 276.00,
                    "validity_days": 28,
                    "general_data_gb": 126.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1500,
                    "special_perks_ar": "126 جيجا نت عام + سوشيال لا محدود",
                    "special_perks_en": "126GB general data + unlimited social"
                },
                {
                    "name_ar": "سوا هيرو",
                    "name_en": "Sawa Hero",
                    "price_base": 360.00,
                    "price_vat": 414.00,
                    "validity_days": 28,
                    "general_data_gb": 9999.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "إنترنت ومكالمات لا محدودة بالكامل بدون سياسة استخدام عادل يومية معلنة",
                    "special_perks_en": "Completely unlimited data and calls with no stated daily cap"
                }
            ]
        },
        {
            "id": "jawwy",
            "name_ar": "جوّي من stc (Jawwy)",
            "name_en": "Jawwy by stc",
            "network": "stc",
            "type": "Digital Brand on stc (علامة رقمية)",
            "website": "https://www.jawwy.sa/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": False,
                "vowifi_notes": "خدمة WiFi Calling غير مفعلة افتراضياً لمعظم خطوط جوّي مقارنة بـ stc سوا، وتعتمد على تحديثات ملف المشغل الخاص بالأجهزة.",
                "volte_supported": True,
                "throttling_fup": "لا يوجد خنق سرعة على الجيجابايت العامة. السوشيال اللامحدود لا يدعم مشاركة الهوتسبوت.",
                "hotspot_policy": "بيانات الهوتسبوت تُخصم حصراً من الرصيد العام.",
                "data_rollover": False,
                "special_feature": "إمكانية مشاركة رصيد البيانات والدقائق بين ما يصل إلى 3 شرائح تحت نفس الحساب عبر التطبيق."
            },
            "packages": [
                {
                    "name_ar": "جوّي 45",
                    "name_en": "Jawwy 45",
                    "price_base": 45.00,
                    "price_vat": 51.75,
                    "validity_days": 30,
                    "general_data_gb": 2.0,
                    "social_data_gb": 2.0,
                    "unlimited_social": False,
                    "local_minutes": 280,
                    "special_perks_ar": "باقة دخول اقتصادية صالحة 30 يوماً",
                    "special_perks_en": "Budget entry plan valid for 30 days"
                },
                {
                    "name_ar": "جوّي 70",
                    "name_en": "Jawwy 70",
                    "price_base": 70.00,
                    "price_vat": 80.50,
                    "validity_days": 30,
                    "general_data_gb": 21.0,
                    "social_data_gb": 20.0,
                    "unlimited_social": False,
                    "local_minutes": 350,
                    "special_perks_ar": "41 جيجابايت إجمالية (21 عام + 20 سوشيال) ومشاركة الرصيد بين الشرائح",
                    "special_perks_en": "41GB total (21GB general + 20GB social), balance sharing across SIMs"
                },
                {
                    "name_ar": "جوّي 90",
                    "name_en": "Jawwy 90",
                    "price_base": 90.00,
                    "price_vat": 103.50,
                    "validity_days": 30,
                    "general_data_gb": 31.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 500,
                    "special_perks_ar": "31 جيجا نت عام + سوشيال ميديا لا محدود على أبراج stc",
                    "special_perks_en": "31GB general data + unlimited social media on stc towers"
                },
                {
                    "name_ar": "جوّي 110",
                    "name_en": "Jawwy 110",
                    "price_base": 110.00,
                    "price_vat": 126.50,
                    "validity_days": 30,
                    "general_data_gb": 45.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1000,
                    "special_perks_ar": "45 جيجا نت عام + سوشيال لا محدود + 1000 دقيقة",
                    "special_perks_en": "45GB general data + unlimited social + 1000 mins"
                },
                {
                    "name_ar": "جوّي 150",
                    "name_en": "Jawwy 150",
                    "price_base": 150.00,
                    "price_vat": 172.50,
                    "validity_days": 30,
                    "general_data_gb": 71.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1000,
                    "special_perks_ar": "71 جيجا نت عام + سوشيال لا محدود",
                    "special_perks_en": "71GB general data + unlimited social"
                },
                {
                    "name_ar": "جوّي 200",
                    "name_en": "Jawwy 200",
                    "price_base": 200.00,
                    "price_vat": 230.00,
                    "validity_days": 30,
                    "general_data_gb": 102.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1300,
                    "special_perks_ar": "102 جيجا نت عام + سوشيال لا محدود + 1300 دقيقة",
                    "special_perks_en": "102GB general data + unlimited social + 1300 mins"
                }
            ]
        },
        {
            "id": "virgin",
            "name_ar": "فيرجن موبايل (Virgin Mobile)",
            "name_en": "Virgin Mobile Saudi",
            "network": "stc",
            "type": "MVNO on stc (مشغل افتراضي)",
            "website": "https://virginmobile.sa/ar/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": False,
                "vowifi_notes": "خدمة VoWiFi غير معتمدة رسمياً لمعظم أجهزة مسبق الدفع لفيرجن.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على باقة البيانات العامة الصافية. باقات السوشيال المفتوح مخصصة للاستخدام الشخصي المباشر.",
                "hotspot_policy": "مشاركة الهوتسبوت تخصم من رصيد البيانات العامة.",
                "data_rollover": False
            },
            "packages": [
                {
                    "name_ar": "فيرجن 45",
                    "name_en": "Virgin 45",
                    "price_base": 45.00,
                    "price_vat": 51.75,
                    "validity_days": 28,
                    "general_data_gb": 3.0,
                    "social_data_gb": 1.0,
                    "unlimited_social": False,
                    "local_minutes": 250,
                    "special_perks_ar": "اقتصادية للمكالمات الخفيفة",
                    "special_perks_en": "Light usage entry plan"
                },
                {
                    "name_ar": "فيرجن 70",
                    "name_en": "Virgin 70",
                    "price_base": 70.00,
                    "price_vat": 80.50,
                    "validity_days": 28,
                    "general_data_gb": 20.0,
                    "social_data_gb": 20.0,
                    "unlimited_social": False,
                    "local_minutes": 350,
                    "special_perks_ar": "40 جيجابايت إجمالية على شبكة stc بسعر 80.5 ريال",
                    "special_perks_en": "40GB total on stc network for 80.50 SAR"
                },
                {
                    "name_ar": "فيرجن 90",
                    "name_en": "Virgin 90",
                    "price_base": 90.00,
                    "price_vat": 103.50,
                    "validity_days": 28,
                    "general_data_gb": 30.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 450,
                    "special_perks_ar": "30 جيجا نت عام + سوشيال ميديا لا محدود",
                    "special_perks_en": "30GB general data + unlimited social"
                },
                {
                    "name_ar": "فيرجن 100",
                    "name_en": "Virgin 100",
                    "price_base": 100.00,
                    "price_vat": 115.00,
                    "validity_days": 28,
                    "general_data_gb": 40.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 750,
                    "special_perks_ar": "أعلى سعة بيانات عامة على شبكة stc في حدود 115 ريال (40 جيجا + سوشيال مفتوح)",
                    "special_perks_en": "Highest general data on stc under 115 SAR (40GB general + unlimited social)"
                },
                {
                    "name_ar": "فيرجن 110",
                    "name_en": "Virgin 110",
                    "price_base": 110.00,
                    "price_vat": 126.50,
                    "validity_days": 28,
                    "general_data_gb": 45.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 745,
                    "special_perks_ar": "45 جيجا نت عام + سوشيال لا محدود",
                    "special_perks_en": "45GB general data + unlimited social"
                },
                {
                    "name_ar": "فيرجن 150",
                    "name_en": "Virgin 150",
                    "price_base": 150.00,
                    "price_vat": 172.50,
                    "validity_days": 28,
                    "general_data_gb": 55.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "55 جيجا نت عام + سوشيال ومكالمات لا محدودة",
                    "special_perks_en": "55GB general data + unlimited social & unlimited calls"
                },
                {
                    "name_ar": "فيرجن 185",
                    "name_en": "Virgin 185",
                    "price_base": 185.00,
                    "price_vat": 212.75,
                    "validity_days": 28,
                    "general_data_gb": 80.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "80 جيجا نت عام + سوشيال ومكالمات لا محدودة",
                    "special_perks_en": "80GB general data + unlimited social & unlimited calls"
                }
            ]
        },
        {
            "id": "mobily",
            "name_ar": "موبايلي (Mobily)",
            "name_en": "Mobily",
            "network": "موبايلي (المشغل الرئيسي)",
            "type": "MNO (مشغل رئيسي)",
            "website": "https://www.mobily.com.sa/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": True,
                "vowifi_notes": "مدعومة رسميًا على خطوط مسبق الدفع (Mobily VoWiFi) للأجهزة المتوافقة.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على حزم البيانات العامة المحددة. باقات السوشيال المفتوح تخضع لسياسة الاستخدام الشخصي المباشر.",
                "hotspot_policy": "الهوتسبوت يُخصم من رصيد البيانات العامة.",
                "data_rollover": False
            },
            "packages": [
                {
                    "name_ar": "موبايلي 30",
                    "name_en": "Mobily 30",
                    "price_base": 30.00,
                    "price_vat": 34.50,
                    "validity_days": 28,
                    "general_data_gb": 1.0,
                    "social_data_gb": 1.0,
                    "unlimited_social": False,
                    "local_minutes": 100,
                    "special_perks_ar": "باقة أساسية خفيفة",
                    "special_perks_en": "Basic light package"
                },
                {
                    "name_ar": "موبايلي 75 (عرض مضاعف)",
                    "name_en": "Mobily 75 (Double Promo)",
                    "price_base": 75.00,
                    "price_vat": 86.25,
                    "validity_days": 28,
                    "general_data_gb": 25.0,
                    "social_data_gb": 21.0,
                    "unlimited_social": False,
                    "local_minutes": 500,
                    "special_perks_ar": "عرض مميز: 25 جيجا عام (10+15) + 21 جيجا سوشيال (10+11) بإجمالي 46 جيجا",
                    "special_perks_en": "Promo: 25GB general (10+15) + 21GB social (10+11), total 46GB"
                },
                {
                    "name_ar": "موبايلي 110",
                    "name_en": "Mobily 110",
                    "price_base": 110.00,
                    "price_vat": 126.50,
                    "validity_days": 28,
                    "general_data_gb": 40.0,
                    "social_data_gb": 60.0,
                    "unlimited_social": False,
                    "local_minutes": 1500,
                    "special_perks_ar": "40 جيجا عام + 60 جيجا سوشيال (إجمالي 100 جيجابايت ضخمة!)",
                    "special_perks_en": "40GB general + 60GB social (Total 100GB!)"
                },
                {
                    "name_ar": "موبايلي 150",
                    "name_en": "Mobily 150",
                    "price_base": 150.00,
                    "price_vat": 172.50,
                    "validity_days": 28,
                    "general_data_gb": 55.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 3000,
                    "special_perks_ar": "55 جيجا نت عام + سوشيال لا محدود + 3000 دقيقة",
                    "special_perks_en": "55GB general + unlimited social + 3000 mins"
                },
                {
                    "name_ar": "موبايلي 150 (بيانات أكثر)",
                    "name_en": "Mobily 150 More Data",
                    "price_base": 150.00,
                    "price_vat": 172.50,
                    "validity_days": 28,
                    "general_data_gb": 70.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1000,
                    "special_perks_ar": "70 جيجا نت عام + سوشيال لا محدود + 1000 دقيقة",
                    "special_perks_en": "70GB general + unlimited social + 1000 mins"
                },
                {
                    "name_ar": "موبايلي 180",
                    "name_en": "Mobily 180",
                    "price_base": 180.00,
                    "price_vat": 207.00,
                    "validity_days": 28,
                    "general_data_gb": 80.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "80 جيجا نت عام + سوشيال ومكالمات لا محدودة",
                    "special_perks_en": "80GB general + unlimited social & calls"
                },
                {
                    "name_ar": "موبايلي 220",
                    "name_en": "Mobily 220",
                    "price_base": 220.00,
                    "price_vat": 253.00,
                    "validity_days": 28,
                    "general_data_gb": 100.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "100 جيجا نت عام + سوشيال ومكالمات لا محدودة",
                    "special_perks_en": "100GB general + unlimited social & calls"
                },
                {
                    "name_ar": "موبايلي 360",
                    "name_en": "Mobily 360",
                    "price_base": 360.00,
                    "price_vat": 414.00,
                    "validity_days": 28,
                    "general_data_gb": 9999.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "إنترنت لا محدود بالكامل ومكالمات لا محدودة",
                    "special_perks_en": "Truly unlimited data & calls"
                }
            ]
        },
        {
            "id": "lebara",
            "name_ar": "ليبارا (Lebara)",
            "name_en": "Lebara Saudi",
            "network": "موبايلي",
            "type": "MVNO on Mobily (مشغل افتراضي)",
            "website": "https://www.lebara.sa/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": False,
                "vowifi_notes": "خدمة VoWiFi غير مفعلة افتراضياً لمعظم خطوط مسبق الدفع لليبارا.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على الجيجابايت العامة المحددة. تطبق سياسة الاستخدام الشخصي.",
                "hotspot_policy": "الهوتسبوت يخصم من البيانات العامة.",
                "data_rollover": False,
                "special_feature": "مكافأة 30% رصيد إضافي مع كل عملية شحن بـ 30 ريال أو أكثر."
            },
            "packages": [
                {
                    "name_ar": "يلا 70",
                    "name_en": "Yalla 70",
                    "price_base": 70.00,
                    "price_vat": 80.50,
                    "validity_days": 30,
                    "general_data_gb": 15.0,
                    "social_data_gb": 20.0,
                    "unlimited_social": False,
                    "local_minutes": 350,
                    "special_perks_ar": "35 جيجا إجمالية صالحة 30 يوماً",
                    "special_perks_en": "35GB total data valid for 30 days"
                },
                {
                    "name_ar": "يلا 90",
                    "name_en": "Yalla 90",
                    "price_base": 90.00,
                    "price_vat": 103.50,
                    "validity_days": 30,
                    "general_data_gb": 35.0,
                    "social_data_gb": 55.0,
                    "unlimited_social": False,
                    "local_minutes": 600,
                    "special_perks_ar": "أعلى كمية بيانات إجمالية في السوق السعودي تحت 105 ريال (90 جيجابايت: 35 عام + 55 سوشيال)",
                    "special_perks_en": "Highest combined data in KSA under 105 SAR (90GB total: 35GB gen + 55GB social)"
                },
                {
                    "name_ar": "فليكس 100",
                    "name_en": "Flex 100",
                    "price_base": 100.00,
                    "price_vat": 115.00,
                    "validity_days": 28,
                    "general_data_gb": 35.0,
                    "social_data_gb": 35.0,
                    "unlimited_social": False,
                    "local_minutes": 900,
                    "special_perks_ar": "70 جيجا إجمالية + 900 دقيقة تشمل مكالمات دولية لـ 10 دول (مصر، السودان، اليمن، إلخ)",
                    "special_perks_en": "70GB total + 900 mins including 10 international destinations"
                },
                {
                    "name_ar": "يلا 110",
                    "name_en": "Yalla 110",
                    "price_base": 110.00,
                    "price_vat": 126.50,
                    "validity_days": 30,
                    "general_data_gb": 40.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1100,
                    "special_perks_ar": "40 جيجا نت عام + سوشيال لا محدود + 1100 دقيقة",
                    "special_perks_en": "40GB general + unlimited social + 1100 mins"
                },
                {
                    "name_ar": "يلا ستريم 125",
                    "name_en": "Yalla Stream 125",
                    "price_base": 125.00,
                    "price_vat": 143.75,
                    "validity_days": 35,
                    "general_data_gb": 50.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1000,
                    "special_perks_ar": "صلاحية 35 يوماً مع ستريم وسوشيال لا محدود و 50 جيجا نت عام",
                    "special_perks_en": "35-day validity, unlimited streaming & social, 50GB general"
                },
                {
                    "name_ar": "يلا 150",
                    "name_en": "Yalla 150",
                    "price_base": 150.00,
                    "price_vat": 172.50,
                    "validity_days": 30,
                    "general_data_gb": 70.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1000,
                    "special_perks_ar": "70 جيجا نت عام + سوشيال لا محدود",
                    "special_perks_en": "70GB general + unlimited social"
                }
            ]
        },
        {
            "id": "zain",
            "name_ar": "زين السعودية (Zain)",
            "name_en": "Zain Saudi Arabia",
            "network": "زين (المشغل الرئيسي)",
            "type": "MNO (مشغل رئيسي)",
            "website": "https://sa.zain.com/ar/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": True,
                "vowifi_notes": "مدعومة رسميًا على باقات شباب ومسبق الدفع للأجهزة المتوافقة.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على رصيد الجيجابايت المحددة. باقات السوشيال المفتوح تخضع للاستخدام الشخصي.",
                "hotspot_policy": "الهوتسبوت يُخصم من البيانات العامة.",
                "data_rollover": False
            },
            "packages": [
                {
                    "name_ar": "شباب 79",
                    "name_en": "Shabab 79",
                    "price_base": 68.70,
                    "price_vat": 79.00,
                    "validity_days": 28,
                    "general_data_gb": 15.0,
                    "social_data_gb": 15.0,
                    "unlimited_social": False,
                    "local_minutes": 500,
                    "special_perks_ar": "السعر النهائي 79 ريال شامل الضريبة تماماً بدون مبالغ كسور",
                    "special_perks_en": "Flat 79 SAR including VAT exactly"
                },
                {
                    "name_ar": "شباب 119",
                    "name_en": "Shabab 119",
                    "price_base": 103.48,
                    "price_vat": 119.00,
                    "validity_days": 28,
                    "general_data_gb": 30.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1500,
                    "special_perks_ar": "30 جيجا نت عام + سوشيال لا محدود + 1500 دقيقة",
                    "special_perks_en": "30GB general + unlimited social + 1500 mins"
                },
                {
                    "name_ar": "شباب 169",
                    "name_en": "Shabab 169",
                    "price_base": 146.96,
                    "price_vat": 169.00,
                    "validity_days": 28,
                    "general_data_gb": 60.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "60 جيجا نت عام + سوشيال لا محدود ومكالمات لا محدودة",
                    "special_perks_en": "60GB general + unlimited social & calls"
                },
                {
                    "name_ar": "شباب 199",
                    "name_en": "Shabab 199",
                    "price_base": 173.04,
                    "price_vat": 199.00,
                    "validity_days": 28,
                    "general_data_gb": 80.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1500,
                    "special_perks_ar": "80 جيجا نت عام + سوشيال لا محدود",
                    "special_perks_en": "80GB general + unlimited social"
                },
                {
                    "name_ar": "شباب 409",
                    "name_en": "Shabab 409",
                    "price_base": 355.65,
                    "price_vat": 409.00,
                    "validity_days": 28,
                    "general_data_gb": 9999.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "إنترنت ومكالمات وسوشيال لا محدود بالكامل",
                    "special_perks_en": "Completely unlimited internet, social & calls"
                }
            ]
        },
        {
            "id": "yaqoot",
            "name_ar": "ياقوت (Yaqoot)",
            "name_en": "Yaqoot by Zain",
            "network": "زين",
            "type": "Digital Brand on Zain (علامة رقمية)",
            "website": "https://yaqoot.sa/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": True,
                "vowifi_notes": "مدعومة عبر شبكة زين للأجهزة المتوافقة، وتخصم من رصيد الدقائق.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على باقة البيانات العامة. تطبيقات السوشيال المختارة غير محدودة بالكامل داخل التطبيقات الرسمية.",
                "hotspot_policy": "الهوتسبوت يُخصم حصراً من البيانات العامة، ولا يُحسب ضمن التطبيقات اللامحدودة!",
                "data_rollover": False,
                "special_feature": "تجربة رقمية بالكامل، مع ميزة إهداء تطبيقات مفتوحة للأصدقاء المشتركين في ياقوت."
            },
            "packages": [
                {
                    "name_ar": "ياقوت 67",
                    "name_en": "Yaqoot 67",
                    "price_base": 58.26,
                    "price_vat": 67.00,
                    "validity_days": 28,
                    "general_data_gb": 7.0,
                    "social_data_gb": 7.0,
                    "unlimited_social": False,
                    "local_minutes": 400,
                    "special_perks_ar": "14 جيجا إجمالية بسعر 67 ريال شامل الضريبة",
                    "special_perks_en": "14GB total for 67 SAR inclusive of VAT"
                },
                {
                    "name_ar": "ياقوت 85",
                    "name_en": "Yaqoot 85",
                    "price_base": 73.91,
                    "price_vat": 85.00,
                    "validity_days": 28,
                    "general_data_gb": 15.0,
                    "social_data_gb": 15.0,
                    "unlimited_social": False,
                    "local_minutes": 750,
                    "special_perks_ar": "30 جيجا إجمالية + 750 دقيقة محلية ودولية",
                    "special_perks_en": "30GB total + 750 local & international mins"
                },
                {
                    "name_ar": "ياقوت 90",
                    "name_en": "Yaqoot 90",
                    "price_base": 78.26,
                    "price_vat": 90.00,
                    "validity_days": 28,
                    "general_data_gb": 30.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "unlimited_apps_count": 7,
                    "local_minutes": 300,
                    "special_perks_ar": "30 جيجا نت عام + 7 تطبيقات لا محدودة (تختار منها YouTube, TikTok, Snap, X, etc.)",
                    "special_perks_en": "30GB general data + 7 unlimited chosen apps (YouTube, TikTok, Snap, etc.)"
                },
                {
                    "name_ar": "ياقوت 103.5",
                    "name_en": "Yaqoot 103.5",
                    "price_base": 90.00,
                    "price_vat": 103.50,
                    "validity_days": 28,
                    "general_data_gb": 56.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": False,
                    "local_minutes": 300,
                    "special_perks_ar": "البطل المطلق للبيانات العامة الصافية: 56 جيجابايت نت عام بدون أي تقييد لتطبيقات",
                    "special_perks_en": "The absolute king of pure general data: 56GB unrestricted data"
                },
                {
                    "name_ar": "ياقوت 125",
                    "name_en": "Yaqoot 125",
                    "price_base": 108.70,
                    "price_vat": 125.00,
                    "validity_days": 28,
                    "general_data_gb": 50.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "unlimited_apps_count": 7,
                    "local_minutes": 500,
                    "special_perks_ar": "50 جيجا نت عام + 7 تطبيقات لا محدودة",
                    "special_perks_en": "50GB general + 7 unlimited apps"
                },
                {
                    "name_ar": "ياقوت 175",
                    "name_en": "Yaqoot 175",
                    "price_base": 152.17,
                    "price_vat": 175.00,
                    "validity_days": 28,
                    "general_data_gb": 75.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "unlimited_apps_count": 7,
                    "local_minutes": 750,
                    "special_perks_ar": "75 جيجا نت عام + 7 تطبيقات لا محدودة",
                    "special_perks_en": "75GB general + 7 unlimited apps"
                },
                {
                    "name_ar": "ياقوت 220.57",
                    "name_en": "Yaqoot 220.57",
                    "price_base": 191.80,
                    "price_vat": 220.57,
                    "validity_days": 28,
                    "general_data_gb": 100.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "unlimited_apps_count": 7,
                    "local_minutes": 1000,
                    "special_perks_ar": "100 جيجا نت عام + 7 تطبيقات لا محدودة",
                    "special_perks_en": "100GB general + 7 unlimited apps"
                },
                {
                    "name_ar": "ياقوت 385",
                    "name_en": "Yaqoot 385",
                    "price_base": 334.78,
                    "price_vat": 385.00,
                    "validity_days": 28,
                    "general_data_gb": 9999.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "إنترنت لا محدود بالكامل ومكالمات لا محدودة",
                    "special_perks_en": "Truly unlimited internet & calls"
                }
            ]
        },
        {
            "id": "salam",
            "name_ar": "سلام موبايل (Salam Mobile)",
            "name_en": "Salam Mobile",
            "network": "زين",
            "type": "MVNO on Zain (مشغل افتراضي)",
            "website": "https://salam.sa/ar/consumer/mobile/prepaid/solo-plans/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": False,
                "vowifi_notes": "خدمة VoWiFi غير مفعلة افتراضياً لمعظم خطوط مسبق الدفع لسلام.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على باقة البيانات العامة.",
                "hotspot_policy": "الهوتسبوت يُخصم من البيانات العامة.",
                "data_rollover": True,
                "data_rollover_notes": "ميزة ترحيل البيانات المتبقية للشهر القادم (حتى 20 جيجا لباقات سولو 74 و 99، وحتى 40 جيجا للباقات الأعلى)."
            },
            "packages": [
                {
                    "name_ar": "سولو 74",
                    "name_en": "Solo 74",
                    "price_base": 74.50,
                    "price_vat": 85.68,
                    "validity_days": 30,
                    "general_data_gb": 20.0,
                    "social_data_gb": 20.0,
                    "unlimited_social": False,
                    "local_minutes": 450,
                    "special_perks_ar": "40 جيجا إجمالية + ترحيل حتى 20 جيجا للشهر التالي + 450 رسالة",
                    "special_perks_en": "40GB total + rollover up to 20GB to next month + 450 SMS"
                },
                {
                    "name_ar": "سولو 99",
                    "name_en": "Solo 99",
                    "price_base": 99.00,
                    "price_vat": 113.85,
                    "validity_days": 30,
                    "general_data_gb": 35.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1000,
                    "special_perks_ar": "35 جيجا نت عام + سوشيال ميديا لا محدود + ترحيل حتى 20 جيجا",
                    "special_perks_en": "35GB general data + unlimited social + rollover up to 20GB"
                },
                {
                    "name_ar": "سولو 149",
                    "name_en": "Solo 149",
                    "price_base": 149.00,
                    "price_vat": 171.35,
                    "validity_days": 30,
                    "general_data_gb": 59.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "59 جيجا عام + سوشيال ومكالمات لا محدودة + ترحيل 25 جيجا",
                    "special_perks_en": "59GB general + unlimited social & calls + 25GB rollover"
                },
                {
                    "name_ar": "سولو 179",
                    "name_en": "Solo 179",
                    "price_base": 179.50,
                    "price_vat": 206.43,
                    "validity_days": 30,
                    "general_data_gb": 79.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "79 جيجا عام + سوشيال ومكالمات لا محدودة + ترحيل 40 جيجا",
                    "special_perks_en": "79GB general + unlimited social & calls + 40GB rollover"
                },
                {
                    "name_ar": "سولو 199",
                    "name_en": "Solo 199",
                    "price_base": 199.00,
                    "price_vat": 228.85,
                    "validity_days": 30,
                    "general_data_gb": 80.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1800,
                    "special_perks_ar": "80 جيجا عام + سوشيال لا محدود + 100 دقيقة دولية + ترحيل 40 جيجا",
                    "special_perks_en": "80GB general + unlimited social + 100 intl mins + 40GB rollover"
                },
                {
                    "name_ar": "سولو اللامحدودة",
                    "name_en": "Solo Infinite",
                    "price_base": 359.00,
                    "price_vat": 412.85,
                    "validity_days": 30,
                    "general_data_gb": 9999.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "إنترنت ومكالمات وسوشيال لا محدود بالكامل",
                    "special_perks_en": "Completely unlimited data, calls & social"
                }
            ]
        },
        {
            "id": "redbull",
            "name_ar": "ريد بُل موبايل (Red Bull MOBILE)",
            "name_en": "Red Bull MOBILE Saudi",
            "network": "زين",
            "type": "MVNO on Zain (مشغل افتراضي)",
            "website": "https://www.redbullmobile.sa/",
            "hidden_conditions": {
                "metering_block_data": "100 KB",
                "metering_block_voice": "بالثانية (Per second)",
                "vowifi_supported": False,
                "vowifi_notes": "خدمة VoWiFi غير معتمدة رسمياً كخدمة قياسية لشرائح ريد بُل.",
                "volte_supported": True,
                "throttling_fup": "لا خنق سرعة على جيجاكوين البيانات العامة.",
                "hotspot_policy": "الهوتسبوت يخصم من رصيد البيانات العامة.",
                "data_rollover": True,
                "data_rollover_notes": "نظام الجيجاكوين (Gigacoins): تتحول جميع البيانات المتبقية غير المستخدمة إلى جيجاكوين لا تنتهي صلاحيتها أبداً طالما شريحتك نشطة!"
            },
            "packages": [
                {
                    "name_ar": "مزاجي 60",
                    "name_en": "Mazaj 60",
                    "price_base": 60.00,
                    "price_vat": 69.00,
                    "validity_days": 30,
                    "general_data_gb": 6.0,
                    "social_data_gb": 6.0,
                    "unlimited_social": False,
                    "local_minutes": 400,
                    "special_perks_ar": "12 جيجاكوين لا تنتهي صلاحيتها",
                    "special_perks_en": "12 Gigacoins that never expire"
                },
                {
                    "name_ar": "مزاجي سمارت 75 (جديد)",
                    "name_en": "Mazaj Smart 75",
                    "price_base": 75.00,
                    "price_vat": 86.25,
                    "validity_days": 28,
                    "general_data_gb": 25.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 400,
                    "special_perks_ar": "25 جيجاكوين عامة لا تنتهي + سوشيال ميديا لا محدود",
                    "special_perks_en": "25 non-expiring Gigacoins + unlimited social media"
                },
                {
                    "name_ar": "مزاجي 80",
                    "name_en": "Mazaj 80",
                    "price_base": 80.00,
                    "price_vat": 92.00,
                    "validity_days": 30,
                    "general_data_gb": 25.0,
                    "social_data_gb": 35.0,
                    "unlimited_social": False,
                    "local_minutes": 500,
                    "special_perks_ar": "60 جيجاكوين إجمالية لا تنتهي صلاحيتها أبداً (25 عام + 35 سوشيال)",
                    "special_perks_en": "60 total non-expiring Gigacoins (25GB gen + 35GB social)"
                },
                {
                    "name_ar": "باقة الضيف 90",
                    "name_en": "Visitor 90",
                    "price_base": 90.00,
                    "price_vat": 103.50,
                    "validity_days": 28,
                    "general_data_gb": 50.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": False,
                    "local_minutes": 300,
                    "special_perks_ar": "50 جيجابايت إنترنت عام صافي بدون تقييد",
                    "special_perks_en": "50GB pure general data without app restrictions"
                },
                {
                    "name_ar": "مزاجي 95",
                    "name_en": "Mazaj 95",
                    "price_base": 95.00,
                    "price_vat": 109.25,
                    "validity_days": 30,
                    "general_data_gb": 35.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 800,
                    "special_perks_ar": "35 جيجاكوين عامة لا تنتهي + سوشيال ميديا لا محدود + 800 دقيقة",
                    "special_perks_en": "35 non-expiring Gigacoins + unlimited social + 800 mins"
                },
                {
                    "name_ar": "مزاجي ماكس 104.3",
                    "name_en": "Mazaj Max 104.3",
                    "price_base": 104.30,
                    "price_vat": 119.95,
                    "validity_days": 30,
                    "general_data_gb": 40.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 950,
                    "special_perks_ar": "40 جيجاكوين عامة + سوشيال ميديا لا محدود",
                    "special_perks_en": "40 Gigacoins + unlimited social"
                },
                {
                    "name_ar": "مزاجي 120",
                    "name_en": "Mazaj 120",
                    "price_base": 120.00,
                    "price_vat": 138.00,
                    "validity_days": 30,
                    "general_data_gb": 50.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 1050,
                    "special_perks_ar": "50 جيجاكوين عامة + سوشيال ميديا لا محدود",
                    "special_perks_en": "50 Gigacoins + unlimited social"
                },
                {
                    "name_ar": "مزاجي 160+",
                    "name_en": "Mazaj 160+",
                    "price_base": 160.00,
                    "price_vat": 184.00,
                    "validity_days": 30,
                    "general_data_gb": 66.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "66 جيجاكوين عامة + سوشيال ومكالمات لا محدودة",
                    "special_perks_en": "66 Gigacoins + unlimited social & calls"
                },
                {
                    "name_ar": "مزاجي 360+",
                    "name_en": "Mazaj 360+",
                    "price_base": 360.00,
                    "price_vat": 414.00,
                    "validity_days": 30,
                    "general_data_gb": 9999.0,
                    "social_data_gb": 0.0,
                    "unlimited_social": True,
                    "local_minutes": 9999,
                    "special_perks_ar": "إنترنت لا محدود + 30 جيجاكوين + مكالمات لا محدودة",
                    "special_perks_en": "Unlimited data + 30 Gigacoins + unlimited calls"
                }
            ]
        }
    ]
}

with open('/home/speedlo/.gemini/antigravity/scratch/saudi-telecom-packages/packages.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Generated packages.json successfully!")
